language: java
addons:
  sonarcloud:
    organization: "bcgov-github"
    token:
      secure: $SONAR_TOKEN
install: mvn compile -Dmaven.javadoc.skip=true -B -V -Popenshift
script:
  - mvn package -Popenshift
  - ./coverage-summary.sh
  - mvn sonar:sonar